### PR TITLE
Toolbar updates

### LINKED ISSUE #122: Show date/time all the time
Show the date/time all the time and remove settings options. Remove unused code and tests.

### LINKED ISSUE #124: Change "X" to "<" on client settings menu
Change affordance for user for closing/hiding the location tree on the client

### PR DESCRIPTION
**Pull request by dnoneill**
closes #122 and closes #124

### CODE REVIEW

**Comment by bretdavidson** [comment]
@dnoneill I'm not seeing the changes in the browser when using the vagrant environment. Does the build need to be updated as well?

**Comment by dnoneill** [comment]
@bretdavidson Yes. Added updated build to branch.

**Comment by jcraitz** [comment]
Looks good to me.  I have one question that's possibly unrelated @dnoneill.  When I `npm run serve`, I see the time and date by default (along with the other changes).  But before and after I run `npm run build`, the vagrant default location at localhost:19679 shows the other changes, but not the time and date by default. I can hide and show the time date to get it to show.

**Comment by dnoneill** [comment]
@jcraitz I don't really understand the question.

**Comment by jcraitz** [comment]
Sorry. When I run the app at localhost:19679/suma/client/, on the vagrant box, I see the other changes, but I don't see the time and date displaying as default.  Am I doing something wrong? 

If I run `npm run serve` and look at localhost:8080, I do see the time and date displayed by default.  I was under the impression that `npm run build` would replace the files in the main suma web folder.  Then they would show up when the vagrant box serves localhost:19679.  Is that not right?

**Comment by dnoneill** [comment]
When you are on the vagrant box, you are going to have to change the branch of Suma it is pulling from. The vagrant box is pulling from new-client, you would have to change that to toolbar-updates if you want to see. Or merge this PR into new-client and pull from the branch to update the code.

**Pull request merged**
