### PR TITLE
PHP 8.1 support

### PR DESCRIPTION
**Pull request by cazzerson**
WIP: this is untested

Attempt to resolve issues that are causing Suma to fail with PHP 8.x. See the mailing list for examples.

* Update dependencies, particularly zf1-future and Gump.
* Remove `get_magic_quotes_gpc()` calls
* Fix phpcs complaints in our code
* Rebuild project
* Document how to use phpcs/PHPCompatibility

### CODE REVIEW

**Comment by jcraitz** [comment]
Hey @cazzerson, I made a [docker version of Suma](https://github.com/jcraitz/Suma-Docker) that's pegged to this branch if that would help you out.  I'm still working on the documentation for it, but I _think_ everything's working with PHP 8.1 and MariaDb 10.5.9.  Note that the Suma code is running on a Debian based php8.1 image.

If you have any problems starting it up or working with it, please let me know!

**Comment by cazzerson** [comment]
@kbeswick we've deployed this to a PHP 8.1 server and everything seems to be working. OK to merge?

**Comment by cazzerson** [comment]
I ran this through a PHP scanner and also selected dependencies that still support PHP 7.1+. I think this can be a minor release, but it may be worth testing on one of your servers if you're still running PHP 7.x.

**Comment by kbeswick** [comment]
This branch works for me on PHP 7.4. I tested things like administering locations/initiatives, using the collection client, and the analysis tools, and they all work without any issues. I think this is good to merge and call a minor release.

**Pull request merged**
