### PR TITLE
Suma PHP 7.3 support

### PR DESCRIPTION
**Pull request by cazzerson**

### CODE REVIEW

**Comment by jcraitz** [comment]
Hi @cazzerson, we're testing this, but not all of us have permissions to merge.

**Comment by jcraitz** [comment]
I'm guessing this PR is needed to fix a bug with Zend in php v7.3?  As far as I can tell the PR doesn't break anything.  @cazzerson, please let me know if there's something specific you want me to check before you merge.

**Comment by cazzerson** [comment]
Thanks @jcraitz! Zend Framework 1 is EOL and incompatible with PHP 7.2+, so I replaced it with a community fork that provides support for newer PHP versions. As a part of this, I started using composer to install ZF1, although I still bundled the code in a new location. I also updated a couple of other dependencies, including guzzle and gump. The tests are basically to see if the server works--can you retrieve data, submit counts, etc.

**Comment by cazzerson** [comment]
@kbeswick @jcraitz this has passed my tests as well

**Pull request merged**
