### PR TITLE
Updating symlink installation documentation

### PR DESCRIPTION
**Pull request by publicus**
Following discussion in PR #76 and follow-up emails about it, I think now that the file-copying instructions and symlink creation instructions in Suma's installation documentation are not in sync with one another. Thus, this PR updates the documentation on creating symlinks in a way that no longer causes the Zend dependency error mentioned in #76.

As a related addition, it also makes explicit which Apache / PHP modules users may need to enable by default.

### CODE REVIEW

**Comment by bretdavidson** [comment]
Thanks for the PR!

A few quick thoughts:

Thanks for adding the [Apache Modules](https://github.com/suma-project/Suma/pull/77/files#diff-9dad486872d77d4486837227d4617cc6R19). Could you modify the PHP version to be something like 5.x.x? PHP 7 isn't supported yet (though we are working on it!).

For consistency with the rest of the documentation, could you edit the instruction to [create](https://github.com/suma-project/Suma/pull/77/files#diff-9dad486872d77d4486837227d4617cc6R41) the directory within the webspace to use "htdocs"? So "/var/www/htdocs/suma"? This is just a convention, sometimes admins name it html and sometimes  htdocs.

For the symlinks, I think only 3 are required:

ln -s /var/www/app/suma/service/web /var/www/htdocs/sumaserver
ln -s /var/www/app/suma/web /var/www/htdocs/suma/client
ln -s /var/www/app/suma/analysis /var/www/htdocs/suma/analysis

**Comment by publicus** [comment]
Thank you for your feedback!

> Could you modify the PHP version to be something like 5.x.x? PHP 7 isn't supported yet (though we are working on it!).

Sure! As of cbbf5b9, the example version is 5.0. (For what it's worth, though, Suma is running well so far on PHP 7 here!)

> For consistency with the rest of the documentation, could you edit the instruction to create the directory within the webspace to use "htdocs"? So "/var/www/htdocs/suma"? This is just a convention, sometimes admins name it html and sometimes htdocs.

Sure, no problem! Changed in d48c7fc.

> For the symlinks, I think only 3 are required:

The fourth symlink, `ln -s /var/www/app/suma/service /var/www/app/sumaserver`, is, it seems, what fixes the Zend dependency error I mentioned gettting in #76 -- when I don't include that fourth symlink, I get the dependency error when I go to `http://localhost/sumaserver/admin/authenticate` in my browser; when I do include that symlink, the error no longer is present.

As I'm reading the existing documentation, the fourth symlink is equivalent to the [Installation instructions'](https://suma-project.github.io/Suma/installation/) file-copying section's note to:

> Copy contents of `/SUMA_DOWNLOAD_DIR/service` to a location outside your web directory. For example, if your web directory is `/var/www/htdocs` you could copy the contents of the `/SUMA_DOWNLOAD_DIR/service` to `/var/www/app/sumaserver`.

**Comment by bretdavidson** [comment]
Thanks for these changes. Regarding the symlinks, the symlink installation process isn't equivalent to the file copying process, only three symlinks are required to configure Suma. If those three aren't working, there is still something still in the configuration files that needs to be changed. For an example, see our [Suma Vagrant](https://github.com/suma-project/Suma-Vagrant) project, which will stand up a virtual machine that you can examine for a successful installation. This machine is provisioned using Ansible, and you can see an [example](https://github.com/suma-project/Suma-Vagrant/blob/master/ansible/roles/demo/tasks/suma.yml#L26-L37) showing how we create the symlinks.

I'm happy to take a look at your configs if needed or discuss this more via e-mail.

Thanks!

**Comment by publicus** [comment]
Ah, ok -- I'll follow-up with an email in a moment with config files; thank you!

**Comment by publicus** [comment]
(And I will also add whatever we find back to the documentation here, to clarify for future users.)

**Comment by publicus** [comment]
Ah, I think I figured out where the confusion arose for me(!): The symlink instructions suggest installing Suma to `/var/www/app/suma/service`, whereas the file copying instructions suggest installing Suma to `/var/www/app/sumaserver`. This is fine, but when reading the instructions in a text editor that doesn't render the Markdown headings clearly, especially not reading top-to-bottom while doing install troubleshooting, I confused the two. All of the config. examples reference the latter and not the former, as well, which is fine, but, I realize now, ended up further confusing me.

I've fixed the config. issue in my installation, and see what you mean now. Thank you!

Because I've read through the installation instructions at least a dozen times and not seen the location discrepancy until now, and then only after closely re-reading the instructions several more times, I suspect that I may not be the only person who gets confused by this. Thus, in 
0a1cd76, I've suggested standardizing the install location across both methods. Does that seem useful to you, too?

**Pull request closed without merging**
