### PR TITLE
add docker scripts

### PR DESCRIPTION
**Pull request by thatbudakguy**
this PR adds scripts for building the full suma stack (server + client) as a [docker](https://www.docker.com/) image, and an example [compose](https://docs.docker.com/compose/) file for running the application with a linked mysql database.

the suma install process seemed complex, with a number of directories to mentally manage, so I put this together in case anyone might benefit from using a prebuilt docker image instead.

the installation can be customized by editing the `Configuration` section of the Dockerfile and rebuilding with something like:
```sh
docker build -t ncsulibrariesdli/suma .
```
some of the config values can be changed at runtime, e.g. `SUMA_DEBUG`, as shown in the compose file.

if docker and docker-compose are installed, running the full app is as easy as:
```sh
docker-compose up -d
```

if this isn't useful; no big deal - just thought i would file the PR in case the project is still active and it would help someone.

### CODE REVIEW

**Comment by bretdavidson** [comment]
Thanks for the pull request! It will be a few days until I can review this, but thanks for the contribution!

**Comment by thatbudakguy** [comment]
No problem! Happy to answer questions about any of it.

**Comment by thatbudakguy** [comment]
added a few comments to the entrypoint script and the ability to set the timezone, since it affects the data timestamps.

**Comment by bretdavidson** [comment]
Sorry for the long delay in responding to this PR and thank you for taking the time to develop these. At this time we are unable to provide support for folks using Suma in containers and are reluctant to include these in the base project. However, if you are interested and willing, I can create a new repo in the Suma organization where you can commit this work as an example for folks to reference. Not ideal from a container user's perspective, but it would still be available for use as a guide.

Please let me know if that sounds suitable to you. Thanks!

**Comment by thatbudakguy** [comment]
no problem - as I understand it, work is in progress on a newer version of Suma anyway. if that's the case, I'll just leave my fork up for awhile in case anyone comes across this issue and is still interested in containerizing the current version of Suma.

**Pull request closed without merging**
